name: Getting Started on Quarkus Build

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
         { 'version': '21', 'opts': '' }
        ]
    name: build with jdk ${{matrix.java.version}}

    steps:
      - uses: actions/checkout@v5
        name: checkout

      - uses: actions/setup-java@v5
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven

      - name: build with maven
        run: mvn -B formatter:validate install --file pom.xml ${{matrix.java.opts}}

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [
          { 'version': '21', 'opts': '' }
        ]
    name: build with jdk ${{matrix.java.version}} windows

    steps:
      - uses: actions/checkout@v5
        name: checkout

      - uses: actions/setup-java@v5
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven

      - name: build with maven
#        Skip integration tests. TestContainers does not support Windows Server 2019: https://github.com/testcontainers/testcontainers-java/issues/2960
        run: mvn -B formatter:validate install --file pom.xml ${{matrix.java.opts}}

